version: "3"
services:
  tipxmr-frontend:
    container_name: "tipxmr-frontend"
    image: node:14
    working_dir: /app
    expose:
      - "8080"
    ports:
      - "8080:8080"
    volumes:
      - ./projects/tipxmr-frontend:/app
    command: npm start

  tipxmr-backend:
    container_name: "tipxmr-backend"
    image: node:14
    working_dir: /app
    expose:
      - "3000"
    ports:
      - "3000:3000"
    volumes:
      - ./projects/tipxmr-backend:/app
    command: npm run watch

  monero-node:
    container_name: "monero-node"
    build:
      context: ./projects/monero-node
    command: --non-interactive --config-file /home/monero/.bitmonero/stagenet.conf
    ports:
      - "38080:38080"
      - "38081:38081"
    volumes:
      - ./projects/monero-node/bitmonero:/home/monero/.bitmonero
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"
