version: "3.9"
services:
  tipxmr-frontend:
    container_name: "tipxmr-frontend"
    build: 
      context: ./projects/tipxmr-frontend
    expose:
      - "8080"
    ports:
      - "8080:8080"
    volumes:
       - ./projects/tipxmr-frontend:/usr/src/app
       - /usr/src/app/node_modules
    command: npm start

  tipxmr-backend:
    container_name: "tipxmr-backend"
    build: 
      context: ./projects/tipxmr-backend
    expose:
      - "3000"
    ports:
      - "3000:3000"
    volumes:
       - ./projects/tipxmr-backend:/usr/src/app
       - /usr/src/app/node_modules
    command: node server.js

  monero-node:
    container_name: "monero-node"
    build: 
      context: ./projects/monero-node
    expose: 
      - "38080"
      - "38081"
    ports: 
    - "38080:38080"
    - "38081:38081"
    volumes:
      - ./projects/monero-node/bitmonero:/home/monero/.bitmonero